# Generated by Django 5.2.5 on 2025-08-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
